### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by ratskrone** [morf/libopts#1]
Hi there!
I appreciate your work. I consider using your lib in my next project. I would like to ask you to add a licence. If you ask me, it is most important to make clear under what conditions your library can be used, copied, shared or distributed. 

Since you offer a library, which may be linked with software already under licence, I recommand Apache License, BSD license or MIT.

Keep me posted when you made up your mind or need help for decision making.

Regards

**Comment by morf** [comment]
Fixed in commit https://github.com/morf/libopts/commit/7084bb88073fb67565f3473b0b57466974bc5ce9
